#!/bin/sh
#sudo docker stop api
#sudo /home/xanvier/bin/dockercontainers_remove
sudo docker build . -t apimysql  
sudo docker run -p 5000:5000/tcp --name api --link mysqlserver:mysql -d apimysql #> /dev/null 2>&1 
#sudo docker inspect $CID | grep IPAddress
 
